name: Build, Analyze, Test Go

on:
  push:
    branches: [ "main" ]
    paths:
      - 'go/**'
      - '.github/workflows/go.yml'

env:
  GO_VERSION: "1.25"
  GO_DIR: ${{ github.workspace }}/go

jobs:

  build-analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      - name: Copy Qodana Config to Root
        run: cp "$GITHUB_WORKSPACE/go/qodana.yaml" "$GITHUB_WORKSPACE/qodana.yaml"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Install Dependencies
        run: go mod tidy
        working-directory: ${{ env.GO_DIR }}

      - name: Build
        run: go build -v ./...
        working-directory: ${{ env.GO_DIR }}

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.2
        with:
          pr-mode: false
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          upload-result: false
          push-fixes: 'none'
          args: |
            --linter,qodana-go,
            --within-docker,false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_GO_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: build-analyze
    defaults:
      run:
        working-directory: ${{ env.GO_DIR }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Run Tests
        run: go test -v ./...
